import SchedulingPaper.TestProcessPolicyAccounting
import SchedulingPaper.AdaptiveRuntimeEndpoint
import SchedulingPaper.ObligatoryRuntimeObjective

/-!
# Exact accounting of the executable AdaptiveThreshold run

This module specializes the policy-sensitive test/process theorem to the
runtime symbols generated by AdaptiveThreshold at `rhoStar`.
-/

namespace SchedulingPaper.Online

noncomputable section

open SchedulingPaper

/-- The generic canonical terminal package for the parameterized adaptive
strategy. -/
theorem run_parameterizedAdaptiveThresholdStrategy_canonicalTrace
    (n : ℕ) (c : ℝ) (cap : Cap)
    (processingTime : Label n → ℝ) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n c) (2 * n + 1)
    result.reason = .strategyStopped ∧
      result.config.TestProcessInvariant ∧
      result.config.transcript.TestsMatch processingTime ∧
      result.config.FixedCompletionInvariant processingTime ∧
      TestProcessTrace result.config.transcript ∧
      ∀ job, result.config.jobs job = .done := by
  unfold run
  rw [parameterizedAdaptiveThresholdStrategy_eq_testProcessStrategy]
  simpa using
    runFuel_testProcessStrategy_completed_with_canonicalTrace
      cap processingTime
      (parameterizedPendingImmediate_selectsLastTest n c) 0

/-- Every terminal test result is literally the corresponding entry of the
fixed input vector, in label order. -/
theorem terminal_testResults_eq_fixedTestResults
    {processingTime : Label n → ℝ} {config : Config n}
    (hstruct : config.TestProcessInvariant)
    (hmatch : config.transcript.TestsMatch processingTime)
    (hdone : ∀ job, config.jobs job = .done) :
    config.transcript.testResults =
      fixedTestResults processingTime := by
  apply List.ext_get
  · rw [hstruct.testResults_length_eq hdone]
    simp
  · intro index hleft hright
    let result := config.transcript.testResults.get ⟨index, hleft⟩
    have horder :
        result.1.val = index := by
      have hmapIndex :
          index <
            (config.transcript.testResults.map
              fun result => result.1.val).length := by
        simpa using hleft
      have hmap :=
        List.getElem_of_eq hstruct.testOrder hmapIndex
      simpa [result, List.get_eq_getElem,
        hstruct.testResults_length_eq hdone] using hmap
    have hlabel :
        result.1 =
          ⟨index, by simpa using hright⟩ :=
      Fin.ext horder
    have hvalue :
        result.2 = processingTime result.1 :=
      hmatch result.1 result.2 (List.get_mem _ _)
    simp only [List.get_eq_getElem]
    have hfixed :
        (fixedTestResults processingTime)[index] =
          (⟨index, by simpa using hright⟩,
            processingTime ⟨index, by simpa using hright⟩) := by
      simp [fixedTestResults]
    rw [hfixed]
    exact Prod.ext hlabel (by simpa [hlabel] using hvalue)

/-- The number of tests before a displayed test is its label index. -/
theorem testsBefore_testResult_eq_label
    {transcript before after : Transcript n}
    (htrace : TestProcessTrace transcript)
    (hallTests : transcript.testResults.length = n)
    (job : Label n) (p : ℝ)
    (hdecomp :
      transcript = before ++ .testResult job p :: after) :
    before.testResults.length = job.val := by
  subst transcript
  have htestOrder := htrace.testOrder
  have hindex :
      before.testResults.length <
        (before ++ .testResult job p :: after).testResults.length := by
    simp
  have hmappedIndex :
      before.testResults.length <
        ((before ++ .testResult job p :: after).testResults.map
          fun result => result.1.val).length := by
    simpa using hindex
  have hget :=
    List.getElem_of_eq htestOrder hmappedIndex
  simp only [Transcript.testResults_append,
    Transcript.testResults_testResult_cons,
    List.map_append, List.map_cons, List.map_nil] at hget
  symm
  simpa [hallTests] using hget

/-- The test-result prefix preceding label `job` is the corresponding prefix
of the fixed result vector. -/
theorem testsBefore_eq_fixedTestResults_take
    {processingTime : Label n → ℝ}
    {config : Config n} {before after : Transcript n}
    (hstruct : config.TestProcessInvariant)
    (hmatch : config.transcript.TestsMatch processingTime)
    (htrace : TestProcessTrace config.transcript)
    (hdone : ∀ job, config.jobs job = .done)
    (job : Label n) (p : ℝ)
    (hdecomp :
      config.transcript =
        before ++ .testResult job p :: after) :
    before.testResults =
      (fixedTestResults processingTime).take job.val := by
  have hall :
      config.transcript.testResults.length = n :=
    hstruct.testResults_length_eq hdone
  have hlength :
      before.testResults.length = job.val :=
    testsBefore_testResult_eq_label htrace hall job p hdecomp
  have hallResults :=
    terminal_testResults_eq_fixedTestResults
      hstruct hmatch hdone
  have htake := congrArg (List.take job.val) hallResults
  rw [hdecomp] at htake
  simp only [Transcript.testResults_append,
    Transcript.testResults_testResult_cons] at htake
  simpa [hlength, List.take_append_of_le_length] using htake

def advanceParameterizedCounters
    (n : ℕ) (c : ℝ)
    (counters : ParameterizedThresholdCounters)
    (results : List (Label n × ℝ)) :
    ParameterizedThresholdCounters :=
  results.foldl
    (fun state result => state.observe n c result.2) counters

theorem buildParameterizedAdaptiveJobs_get_threshold
    (n : ℕ) (counters : ParameterizedThresholdCounters)
    (results : List (Label n × ℝ))
    (index : ℕ) (hindex : index < results.length) :
    ((buildParameterizedAdaptiveJobs n counters results).get
        ⟨index, by simpa using hindex⟩).threshold =
      (advanceParameterizedCounters n rhoStar counters
        (results.take index)).threshold n rhoStar := by
  induction results generalizing counters index with
  | nil =>
      simp at hindex
  | cons result results ih =>
      cases index with
      | zero =>
          simp [buildParameterizedAdaptiveJobs,
            advanceParameterizedCounters]
      | succ index =>
          have htail : index < results.length := by
            simpa using hindex
          simpa [buildParameterizedAdaptiveJobs,
            advanceParameterizedCounters] using
            ih
              (counters.observe n rhoStar result.2)
              index htail

theorem advance_initial_eq_parameterizedCountersFromResults
    (n : ℕ) (results : List (Label n × ℝ)) :
    advanceParameterizedCounters n rhoStar
        ParameterizedThresholdCounters.initial results =
      parameterizedCountersFromResults n rhoStar results := rfl

/-- The live threshold stored in the runtime record is exactly the threshold
reconstructed from all preceding public tests. -/
theorem adaptiveRuntimeJob_threshold_eq_prefixCounters
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job)
    (job : Label n) :
    let runtimeJob :=
      (adaptiveRuntimeJobs processingTime).get
        ⟨job.val, by simpa using job.isLt⟩
    runtimeJob.threshold =
      (parameterizedCountersFromResults n rhoStar
        ((fixedTestResults processingTime).take job.val)).threshold
        n rhoStar := by
  dsimp only
  have hjobs :=
    adaptiveRuntimeJobs_eq_buildParameterizedAdaptiveJobs
      processingTime hnonneg
  have hindex :
      job.val < (adaptiveRuntimeJobs processingTime).length := by
    simpa using job.isLt
  have hget :=
    List.getElem_of_eq hjobs hindex
  have hthreshold := congrArg AdaptiveRuntimeJob.threshold hget
  simp only [List.get_eq_getElem] at hthreshold ⊢
  rw [hthreshold]
  simpa [advance_initial_eq_parameterizedCountersFromResults] using
    buildParameterizedAdaptiveJobs_get_threshold
      n ParameterizedThresholdCounters.initial
      (fixedTestResults processingTime)
      job.val (by simpa using job.isLt)

/-- Runtime outcome indexed directly by the original online label. -/
def adaptiveRuntimeOutcomeByLabel
    (processingTime : Label n → ℝ) (job : Label n) :
    BoundaryOutcome :=
  ((adaptiveRuntimeJobs processingTime).get
    ⟨job.val, by simpa using job.isLt⟩).symbol.outcome

theorem adaptiveRuntimeOutcomeByLabel_deferred_iff
    (processingTime : Label n → ℝ) (job : Label n) :
    adaptiveRuntimeOutcomeByLabel processingTime job = .deferred ↔
      ((adaptiveRuntimeJobs processingTime).get
        ⟨job.val, by simpa using job.isLt⟩).symbol = .deferred := by
  unfold adaptiveRuntimeOutcomeByLabel
  generalize
    (adaptiveRuntimeJobs processingTime).get
      ⟨job.val, by simpa using job.isLt⟩ = runtimeJob
  cases runtimeJob.symbol <;>
    simp [ObligatoryRuntimeClass.outcome]

theorem adaptiveRuntimeJob_processing_eq
    (processingTime : Label n → ℝ) (job : Label n) :
    ((adaptiveRuntimeJobs processingTime).get
      ⟨job.val, by simpa using job.isLt⟩).processing =
        processingTime job := by
  have hmap :=
    buildAdaptiveJobs_map_result
      (initialAnalysisState n)
      (fixedTestResults processingTime)
  have hmapped :
      (adaptiveRuntimeJobs processingTime).map
          (fun runtimeJob =>
            (runtimeJob.label, runtimeJob.processing)) =
        fixedTestResults processingTime := by
    simpa [adaptiveRuntimeJobs] using hmap
  have hindex :
      job.val <
        ((adaptiveRuntimeJobs processingTime).map
          (fun runtimeJob =>
            (runtimeJob.label, runtimeJob.processing))).length := by
    simpa using job.isLt
  have hget := List.getElem_of_eq hmapped hindex
  simpa [fixedTestResults] using congrArg Prod.snd hget

theorem adaptiveRuntimeJob_threshold_nonneg
    (processingTime : Label n → ℝ) (job : Label n) :
    0 ≤
      ((adaptiveRuntimeJobs processingTime).get
        ⟨job.val, by simpa using job.isLt⟩).threshold := by
  let index : Fin (adaptiveRuntimeSymbols processingTime).length :=
    ⟨job.val, by simpa using job.isLt⟩
  have hthreshold :=
    adaptiveRuntimeJob_threshold processingTime index
  rw [hthreshold]
  exact
    obligatorySymbolThresholdFn_nonneg
      (adaptiveRuntimeSymbols processingTime) index

/-- The executable pending selector after a displayed test agrees exactly
with the runtime symbol attached to that label. -/
theorem parameterizedPendingImmediate_after_test_eq_runtimeSymbol
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job)
    {config : Config n} {before after : Transcript n}
    (hstruct : config.TestProcessInvariant)
    (hmatch : config.transcript.TestsMatch processingTime)
    (htrace : TestProcessTrace config.transcript)
    (hdone : ∀ job, config.jobs job = .done)
    (job : Label n) (p : ℝ)
    (hdecomp :
      config.transcript =
        before ++ Observation.testResult job p :: after) :
    Transcript.parameterizedPendingImmediate?
        n rhoStar (before ++ [Observation.testResult job p]) =
      if adaptiveRuntimeOutcomeByLabel processingTime job = .deferred
        then none else some job := by
  let runtimeJob :=
    (adaptiveRuntimeJobs processingTime).get
      ⟨job.val, by simpa using job.isLt⟩
  have hp : p = processingTime job := by
    apply hmatch job p
    apply
      (testResult_mem_iff_observation_mem
        config.transcript job p).2
    rw [hdecomp]
    simp
  have hprefix :=
    testsBefore_eq_fixedTestResults_take
      hstruct hmatch htrace hdone job p hdecomp
  have hthreshold :=
    adaptiveRuntimeJob_threshold_eq_prefixCounters
      processingTime hnonneg job
  have hprocessing :
      runtimeJob.processing = p := by
    rw [adaptiveRuntimeJob_processing_eq processingTime job, hp]
  have hclass :
      classifyAdaptive runtimeJob.threshold runtimeJob.processing =
        runtimeJob.symbol := by
    apply buildAdaptiveJobs_classification
    exact List.get_mem _ _
  have hthresholdNonneg :
      0 ≤ runtimeJob.threshold :=
    adaptiveRuntimeJob_threshold_nonneg processingTime job
  have hcounters :
      Transcript.parameterizedCountersBeforeLastTest
          n rhoStar (before ++ [Observation.testResult job p]) =
        parameterizedCountersFromResults n rhoStar
          before.testResults := by
    unfold Transcript.parameterizedCountersBeforeLastTest
    simp
  have hpendingFormula :
      Transcript.parameterizedPendingImmediate?
          n rhoStar (before ++ [Observation.testResult job p]) =
        if p ≤ runtimeJob.threshold then some job else none := by
    unfold Transcript.parameterizedPendingImmediate?
    rw [List.getLast?_concat]
    simp only
    rw [hcounters, hprefix, ← hthreshold]
  cases hsymbol : runtimeJob.symbol with
  | zero =>
      have hzero :
          runtimeJob.processing = 0 :=
        (classifyAdaptive_eq_zero_iff
          runtimeJob.threshold runtimeJob.processing).mp
          (hclass.trans hsymbol)
      have hple : p ≤ runtimeJob.threshold := by
        rw [← hprocessing, hzero]
        exact hthresholdNonneg
      rw [hpendingFormula]
      change
        (if p ≤ runtimeJob.threshold then some job else none) =
          if runtimeJob.symbol.outcome = .deferred
            then none else some job
      rw [hsymbol]
      simp [hple, ObligatoryRuntimeClass.outcome]
  | immediate =>
      have hple :
          p ≤ runtimeJob.threshold := by
        rw [← hprocessing]
        exact
          ((classifyAdaptive_eq_immediate_iff
            runtimeJob.threshold runtimeJob.processing).mp
            (hclass.trans hsymbol)).2
      rw [hpendingFormula]
      change
        (if p ≤ runtimeJob.threshold then some job else none) =
          if runtimeJob.symbol.outcome = .deferred
            then none else some job
      rw [hsymbol]
      simp [hple, ObligatoryRuntimeClass.outcome]
  | deferred =>
      have hgt :
          runtimeJob.threshold < p := by
        rw [← hprocessing]
        exact
          ((classifyAdaptive_eq_deferred_iff
            runtimeJob.threshold runtimeJob.processing).mp
            (hclass.trans hsymbol)).2
      rw [hpendingFormula]
      change
        (if p ≤ runtimeJob.threshold then some job else none) =
          if runtimeJob.symbol.outcome = .deferred
            then none else some job
      rw [hsymbol]
      simp [not_le.mpr hgt, ObligatoryRuntimeClass.outcome]

theorem adaptiveRuntime_immediateFor
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job)
    {config : Config n}
    (hstruct : config.TestProcessInvariant)
    (hmatch : config.transcript.TestsMatch processingTime)
    (htrace : TestProcessTrace config.transcript)
    (hdone : ∀ job, config.jobs job = .done)
    (job : Label n)
    (hjob :
      adaptiveRuntimeOutcomeByLabel processingTime job ≠ .deferred) :
    config.transcript.ImmediateFor
      (fun transcript =>
        transcript.parameterizedPendingImmediate? n rhoStar) job := by
  intro before after p hdecomp
  change
    Transcript.parameterizedPendingImmediate?
      n rhoStar (before ++ [Observation.testResult job p]) =
        some job
  rw [parameterizedPendingImmediate_after_test_eq_runtimeSymbol
    processingTime hnonneg hstruct hmatch htrace hdone
      job p hdecomp]
  simp [hjob]

theorem adaptiveRuntime_deferredFor
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job)
    {config : Config n}
    (hstruct : config.TestProcessInvariant)
    (hmatch : config.transcript.TestsMatch processingTime)
    (htrace : TestProcessTrace config.transcript)
    (hdone : ∀ job, config.jobs job = .done)
    (job : Label n)
    (hjob :
      adaptiveRuntimeOutcomeByLabel processingTime job = .deferred) :
    config.transcript.DeferredFor
      (fun transcript =>
        transcript.parameterizedPendingImmediate? n rhoStar) job := by
  intro before after p hdecomp
  change
    Transcript.parameterizedPendingImmediate?
      n rhoStar (before ++ [Observation.testResult job p]) =
        none
  rw [parameterizedPendingImmediate_after_test_eq_runtimeSymbol
    processingTime hnonneg hstruct hmatch htrace hdone
      job p hdecomp]
  simp [hjob]

theorem adaptiveRuntime_deferred_nonzero
    (processingTime : Label n → ℝ) (job : Label n)
    (hjob :
      adaptiveRuntimeOutcomeByLabel processingTime job = .deferred) :
    processingTime job ≠ 0 := by
  let runtimeJob :=
    (adaptiveRuntimeJobs processingTime).get
      ⟨job.val, by simpa using job.isLt⟩
  have hsymbol :
      runtimeJob.symbol = .deferred := by
    exact
      (adaptiveRuntimeOutcomeByLabel_deferred_iff
        processingTime job).mp hjob
  have hclass :
      classifyAdaptive runtimeJob.threshold runtimeJob.processing =
        runtimeJob.symbol := by
    apply buildAdaptiveJobs_classification
    exact List.get_mem _ _
  have hnonzero :
      runtimeJob.processing ≠ 0 :=
    ((classifyAdaptive_eq_deferred_iff
      runtimeJob.threshold runtimeJob.processing).mp
      (hclass.trans hsymbol)).1
  rwa [adaptiveRuntimeJob_processing_eq processingTime job] at hnonzero

theorem run_parameterizedAdaptiveThresholdStrategy_completionLabels_perm
    (n : ℕ) (cap : Cap)
    (processingTime : Label n → ℝ) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
    (result.config.transcript.completionLabels processingTime).Perm
      (List.ofFn id) := by
  dsimp only
  let result :=
    run cap (fixedOracle processingTime)
      (parameterizedAdaptiveThresholdStrategy n rhoStar)
      (2 * n + 1)
  have hrun :=
    run_parameterizedAdaptiveThresholdStrategy_canonicalTrace
      n rhoStar cap processingTime
  have hnodup :
      (result.config.transcript.completionLabels
        processingTime).Nodup :=
    hrun.2.2.2.1.nodup
  have hmem :
      ∀ job,
        job ∈ result.config.transcript.completionLabels
          processingTime := by
    intro job
    rw [hrun.2.2.2.1.mem_iff]
    simp [hrun.2.2.2.2.2 job,
      JobState.completionRecorded]
  apply
    (List.perm_ext_iff_of_nodup hnodup
      (List.nodup_ofFn.mpr Function.injective_id)).mpr
  intro job
  simp [hmem job]

theorem run_parameterizedAdaptiveThresholdStrategy_pairCharge_eq
    (n : ℕ) (cap : Cap)
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job)
    {left right : Label n} (horder : left < right) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
    tracePairCharge cap processingTime
        result.config.transcript left right =
      obligatoryALGPairCharge
        ⟨adaptiveRuntimeOutcomeByLabel processingTime left,
          processingTime left⟩
        ⟨adaptiveRuntimeOutcomeByLabel processingTime right,
          processingTime right⟩ := by
  dsimp only
  let result :=
    run cap (fixedOracle processingTime)
      (parameterizedAdaptiveThresholdStrategy n rhoStar)
      (2 * n + 1)
  have hrun :=
    run_parameterizedAdaptiveThresholdStrategy_canonicalTrace
      n rhoStar cap processingTime
  have hallTests :
      result.config.transcript.testResults.length = n :=
    hrun.2.1.testResults_length_eq hrun.2.2.2.2.2
  have hallProcessed :
      ∀ job, job ∈ result.config.transcript.processedLabels := by
    intro job
    rw [← hrun.2.1.done_iff job]
    exact hrun.2.2.2.2.2 job
  have hfollow :
      result.config.transcript.FollowsStrategy
        (testProcessStrategy
          (fun transcript =>
            transcript.parameterizedPendingImmediate? n rhoStar)) := by
    simpa [result,
      parameterizedAdaptiveThresholdStrategy_eq_testProcessStrategy] using
      run_followsStrategy cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
  exact
    hrun.2.2.2.2.1.tracePairCharge_eq_obligatoryALGPairCharge
      hrun.2.2.1 hallTests hallProcessed hfollow
      (parameterizedPendingImmediate_selectsLastTest n rhoStar)
      (adaptiveRuntimeOutcomeByLabel processingTime)
      (adaptiveRuntime_immediateFor processingTime hnonneg
        hrun.2.1 hrun.2.2.1 hrun.2.2.2.2.1
          hrun.2.2.2.2.2)
      (adaptiveRuntime_deferredFor processingTime hnonneg
        hrun.2.1 hrun.2.2.1 hrun.2.2.2.2.1
          hrun.2.2.2.2.2)
      (adaptiveRuntime_deferred_nonzero processingTime)
      cap horder

/-- Exact diagonal-plus-status-pairs formula for the concrete run. -/
theorem run_parameterizedAdaptiveThresholdStrategy_completionCost_eq_statusPairs
    (n : ℕ) (cap : Cap)
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
    runCompletionCost cap processingTime result =
      Finset.univ.sum
          (fun job : Label n => (1 : ℝ) + processingTime job) +
        Finset.univ.sum (fun left : Label n =>
          (Finset.univ.filter
            (fun right : Label n => left < right)).sum
              (fun right =>
                obligatoryALGPairCharge
                  ⟨adaptiveRuntimeOutcomeByLabel
                      processingTime left,
                    processingTime left⟩
                  ⟨adaptiveRuntimeOutcomeByLabel
                      processingTime right,
                    processingTime right⟩)) := by
  dsimp only
  let result :=
    run cap (fixedOracle processingTime)
      (parameterizedAdaptiveThresholdStrategy n rhoStar)
      (2 * n + 1)
  have hrun :=
    run_parameterizedAdaptiveThresholdStrategy_canonicalTrace
      n rhoStar cap processingTime
  have hallTests :
      result.config.transcript.testResults.length = n :=
    hrun.2.1.testResults_length_eq hrun.2.2.2.2.2
  have hallProcessed :
      ∀ job, job ∈ result.config.transcript.processedLabels := by
    intro job
    rw [← hrun.2.1.done_iff job]
    exact hrun.2.2.2.2.2 job
  have hperm :
      (result.config.transcript.completionLabels
        processingTime).Perm (List.ofFn id) := by
    simpa [result] using
      run_parameterizedAdaptiveThresholdStrategy_completionLabels_perm
        n cap processingTime
  have hdecomposition :=
    completionCost_eq_traceSelf_add_pairs cap processingTime
      result.config.transcript hperm
  have hself :
      ∀ job : Label n,
        traceSelfCharge cap processingTime
            result.config.transcript job =
          1 + processingTime job := by
    intro job
    apply traceSelfCharge_eq_one_add_of_projection
    · exact
        hrun.2.2.2.2.1.terminal_selfProjection
          hrun.2.2.1 hallTests hallProcessed job
    · rfl
  unfold runCompletionCost
  rw [hdecomposition]
  apply congrArg₂ (· + ·)
  · apply Finset.sum_congr rfl
    intro job _hjob
    exact hself job
  · apply Finset.sum_congr rfl
    intro left _hleft
    apply Finset.sum_congr rfl
    intro right hright
    exact
      run_parameterizedAdaptiveThresholdStrategy_pairCharge_eq
        n cap processingTime hnonneg
        (Finset.mem_filter.mp hright).2

private theorem obligatoryALG_pair_rows_ofFn
    {n : ℕ} (outcome : Fin (n + 1) → BoundaryOutcome)
    (processing : Fin (n + 1) → ℝ) :
    (∑ i : Fin (n + 1),
      ∑ j ∈ Finset.univ.filter (fun j => i < j),
        obligatoryALGPairCharge
          ⟨outcome i, processing i⟩
          ⟨outcome j, processing j⟩) =
      (∑ j : Fin n,
        obligatoryALGPairCharge
          ⟨outcome 0, processing 0⟩
          ⟨outcome j.succ, processing j.succ⟩) +
      ∑ i : Fin n, ∑ j ∈ Finset.univ.filter (fun j => i < j),
        obligatoryALGPairCharge
          ⟨outcome i.succ, processing i.succ⟩
          ⟨outcome j.succ, processing j.succ⟩ := by
  rw [Fin.sum_univ_succ]
  congr 1
  · classical
    simp_rw [Finset.sum_filter]
    rw [Fin.sum_univ_succ]
    simp
  · apply Finset.sum_congr rfl
    intro i _hi
    classical
    simp_rw [Finset.sum_filter]
    rw [Fin.sum_univ_succ]
    simp

/-- Finite-index normal form of the recursive obligatory online pair
objective. -/
theorem obligatoryALGPairObjective_jobsOfFunctions_eq_finSums
    {n : ℕ} (outcome : Fin n → BoundaryOutcome)
    (processing : Fin n → ℝ) :
    obligatoryALGPairObjective
        (obligatoryJobsOfFunctions outcome processing) =
      Finset.univ.sum
          (fun i : Fin n => (1 : ℝ) + processing i) +
        Finset.univ.sum (fun i : Fin n =>
          (Finset.univ.filter
            (fun j : Fin n => i < j)).sum
              (fun j =>
                obligatoryALGPairCharge
                  ⟨outcome i, processing i⟩
                  ⟨outcome j, processing j⟩)) := by
  induction n with
  | zero =>
      simp [obligatoryJobsOfFunctions,
        obligatoryALGPairObjective]
  | succ n ih =>
      let tailOutcome : Fin n → BoundaryOutcome :=
        fun i => outcome i.succ
      let tailProcessing : Fin n → ℝ :=
        fun i => processing i.succ
      have htail := ih tailOutcome tailProcessing
      rw [show obligatoryJobsOfFunctions outcome processing =
          ⟨outcome 0, processing 0⟩ ::
            obligatoryJobsOfFunctions tailOutcome tailProcessing by
        simp [obligatoryJobsOfFunctions, tailOutcome,
          tailProcessing, List.ofFn_succ]]
      simp only [obligatoryALGPairObjective]
      have hrow :
          (List.map
            (obligatoryALGPairCharge
              ⟨outcome 0, processing 0⟩)
            (obligatoryJobsOfFunctions
              tailOutcome tailProcessing)).sum =
            ∑ j : Fin n,
              obligatoryALGPairCharge
                ⟨outcome 0, processing 0⟩
                ⟨tailOutcome j, tailProcessing j⟩ := by
        unfold obligatoryJobsOfFunctions
        rw [List.map_ofFn, List.sum_ofFn]
        rfl
      rw [hrow, htail, Fin.sum_univ_succ,
        obligatoryALG_pair_rows_ofFn]
      dsimp [tailOutcome, tailProcessing]
      ring

/-- The concrete completion cost is exactly the recursive obligatory online
objective of its runtime word. -/
theorem run_parameterizedAdaptiveThresholdStrategy_completionCost_eq_obligatoryALG
    (n : ℕ) (cap : Cap)
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
    runCompletionCost cap processingTime result =
      obligatoryALGPairObjective
        (obligatoryJobsOfFunctions
          (adaptiveRuntimeOutcomeByLabel processingTime)
          processingTime) := by
  dsimp only
  rw [run_parameterizedAdaptiveThresholdStrategy_completionCost_eq_statusPairs
    n cap processingTime hnonneg]
  exact
    (obligatoryALGPairObjective_jobsOfFunctions_eq_finSums
      (adaptiveRuntimeOutcomeByLabel processingTime)
      processingTime).symm

theorem obligatoryJobsOfFunctions_adaptiveRuntimeByLabel
    (processingTime : Label n → ℝ) :
    obligatoryJobsOfFunctions
        (adaptiveRuntimeOutcomeByLabel processingTime)
        processingTime =
      (adaptiveRuntimeJobs processingTime).map
        (fun runtimeJob =>
          {
            outcome := runtimeJob.symbol.outcome
            processing := runtimeJob.processing
          }) := by
  apply List.ext_get
  · simp [obligatoryJobsOfFunctions]
  · intro index hleft hright
    simp only [List.get_eq_getElem]
    have hindex :
        index < (adaptiveRuntimeJobs processingTime).length := by
      simpa using hright
    let job : Label n :=
      ⟨index, by simpa using hindex⟩
    have hprocessing :=
      adaptiveRuntimeJob_processing_eq processingTime job
    simp [obligatoryJobsOfFunctions,
      adaptiveRuntimeOutcomeByLabel, job] at hprocessing ⊢
    exact hprocessing.symm

theorem obligatoryJobsOfFunctions_adaptiveRuntimeSymbolic
    (processingTime : Label n → ℝ) :
    obligatoryJobsOfFunctions
        (obligatorySymbolOutcomeFn
          (adaptiveRuntimeSymbols processingTime))
        (adaptiveRuntimeProcessing processingTime) =
      (adaptiveRuntimeJobs processingTime).map
        (fun runtimeJob =>
          {
            outcome := runtimeJob.symbol.outcome
            processing := runtimeJob.processing
          }) := by
  apply List.ext_get
  · simp [obligatoryJobsOfFunctions]
  · intro index hleft hright
    simp only [List.get_eq_getElem]
    let symbolicIndex :
        Fin (adaptiveRuntimeSymbols processingTime).length :=
      ⟨index, by simpa [obligatoryJobsOfFunctions] using hleft⟩
    let runtimeIndex : Label n :=
      ⟨index, by simpa using hright⟩
    have hsymbol :=
      adaptiveRuntimeJob_symbol processingTime symbolicIndex
    have hprocessing :=
      (adaptiveRuntimeJobs_get_label_processing
        processingTime symbolicIndex).2
    have hlabel :=
      (adaptiveRuntimeJobs_get_label_processing
        processingTime symbolicIndex).1
    simp [obligatoryJobsOfFunctions,
      obligatorySymbolOutcomeFn, symbolicIndex,
      adaptiveRuntimeProcessing] at hsymbol hprocessing ⊢
    rw [hsymbol, hprocessing]
    exact ⟨rfl, rfl⟩

theorem obligatoryJobsOfFunctions_adaptiveRuntime_eq_symbolic
    (processingTime : Label n → ℝ) :
    obligatoryJobsOfFunctions
        (adaptiveRuntimeOutcomeByLabel processingTime)
        processingTime =
      obligatoryJobsOfFunctions
        (obligatorySymbolOutcomeFn
          (adaptiveRuntimeSymbols processingTime))
        (adaptiveRuntimeProcessing processingTime) := by
  rw [obligatoryJobsOfFunctions_adaptiveRuntimeByLabel,
    obligatoryJobsOfFunctions_adaptiveRuntimeSymbolic]

theorem run_parameterizedAdaptiveThresholdStrategy_completionCost_eq_symbolicALG
    (n : ℕ) (cap : Cap)
    (processingTime : Label n → ℝ)
    (hnonneg : ∀ job, 0 ≤ processingTime job) :
    let result :=
      run cap (fixedOracle processingTime)
        (parameterizedAdaptiveThresholdStrategy n rhoStar)
        (2 * n + 1)
    runCompletionCost cap processingTime result =
      obligatoryALGPairObjective
        (obligatoryJobsOfFunctions
          (obligatorySymbolOutcomeFn
            (adaptiveRuntimeSymbols processingTime))
          (adaptiveRuntimeProcessing processingTime)) := by
  dsimp only
  rw [run_parameterizedAdaptiveThresholdStrategy_completionCost_eq_obligatoryALG
    n cap processingTime hnonneg,
    obligatoryJobsOfFunctions_adaptiveRuntime_eq_symbolic]

end

end SchedulingPaper.Online
