import SchedulingPaper.RevealingOptimizationQuotaCanonicalTrace
import Mathlib.Tactic

/-!
# Owner restriction of a revealing quota trace

The physical pilot compiler deletes every operation owned by a sampled job
from a canonical virtual quota run.  This file establishes the operational
fact behind that compiler: after owner deletion, the remaining word is still
generated by a transcript-only quota policy which simply skips deleted
labels.
-/

namespace SchedulingPaper
namespace RevealingOptimization
namespace QuotaRestriction

open Online
open RandomizedOptional
open QuotaStrategy

noncomputable section
attribute [local instance] Classical.propDecidable

/-- First untouched label satisfying both the phase predicate and the fixed
owner predicate. -/
def nextKeptTouch?
    (n : ℕ) (keep : Fin n → Prop) [DecidablePred keep]
    (eligible : Fin n → Bool) (transcript : Online.Transcript n) :
    Option (Fin n) :=
  (List.finRange n).find? fun job =>
    eligible job && decide (keep job) &&
      decide (job ∉ transcript.startedLabels)

/-- The canonical quota policy restricted to a fixed set of owners.  Its
quota is still expressed in the original virtual labels: deleted test slots
are not refilled. -/
def keptQuotaStrategy
    (n q : ℕ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep] : Online.Strategy n :=
  fun transcript =>
    match safeLastLowPending? low transcript with
    | some job => some (.process job)
    | none =>
        match nextKeptTouch? n keep
            (fun job => decide (job.val < q)) transcript with
        | some job => some (.test job)
        | none =>
            match transcript.shortestRemaining? with
            | some job => some (.process job)
            | none =>
                (nextKeptTouch? n keep
                  (fun job => decide (q ≤ job.val)) transcript).map
                    Online.Action.raw

theorem nextKeptTouch?_eq_some
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (eligible : Fin n → Bool) (transcript : Online.Transcript n)
    (job : Fin n) (hkeep : keep job) (heligible : eligible job = true)
    (hnew : job ∉ transcript.startedLabels)
    (hearlier : ∀ other : Fin n, other.val < job.val →
      keep other → other ∈ transcript.startedLabels) :
    nextKeptTouch? n keep eligible transcript = some job := by
  unfold nextKeptTouch?
  rw [List.find?_eq_some_iff_getElem]
  constructor
  · simp [heligible, hkeep, hnew]
  · refine ⟨job.val, ?_, ?_, ?_⟩
    · simp
    · apply Fin.ext
      simp
    · intro j hj
      have hjn : j < n := lt_trans hj job.isLt
      let other : Fin n := ⟨j, hjn⟩
      by_cases hother : keep other
      · have hstarted : other ∈ transcript.startedLabels := by
          apply hearlier other
          · simpa [other] using hj
          · exact hother
        have hget : (List.finRange n)[j]'(by simp [hjn]) = other := by
          apply Fin.ext
          simp [other]
        rw [hget]
        simp [hstarted]
      · have hget : (List.finRange n)[j]'(by simp [hjn]) = other := by
          apply Fin.ext
          simp [other]
        rw [hget]
        simp [hother]

theorem nextKeptTouch?_eq_none
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (eligible : Fin n → Bool) (transcript : Online.Transcript n)
    (hdone : ∀ job : Fin n, eligible job = true → keep job →
      job ∈ transcript.startedLabels) :
    nextKeptTouch? n keep eligible transcript = none := by
  unfold nextKeptTouch?
  rw [List.find?_eq_none]
  intro job _
  cases heligible : eligible job with
  | false => simp [heligible]
  | true =>
      by_cases hkeep : keep job
      · have hstarted := hdone job heligible hkeep
        simp [heligible, hkeep, hstarted]
      · simp [heligible, hkeep]

@[simp] theorem testResults_filter_owner
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (transcript : Online.Transcript n) :
    Online.Transcript.testResults
      (transcript.filter (fun observation : Online.Observation n =>
        keep observation.ownerLabel)) =
      transcript.testResults.filter fun result => keep result.1 := by
  induction transcript with
  | nil => rfl
  | cons observation rest ih =>
      rw [List.filter_cons]
      by_cases hkeep : keep observation.ownerLabel
      · rw [if_pos (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.testResults,
            Online.Observation.testResult?, Online.Observation.ownerLabel]
      · rw [if_neg (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.testResults,
            Online.Observation.testResult?, Online.Observation.ownerLabel]

@[simp] theorem processedLabels_filter_owner
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (transcript : Online.Transcript n) :
    Online.Transcript.processedLabels
      (transcript.filter (fun observation : Online.Observation n =>
        keep observation.ownerLabel)) =
      transcript.processedLabels.filter keep := by
  induction transcript with
  | nil => rfl
  | cons observation rest ih =>
      rw [List.filter_cons]
      by_cases hkeep : keep observation.ownerLabel
      · rw [if_pos (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.processedLabels,
            Online.Observation.ownerLabel]
      · rw [if_neg (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.processedLabels,
            Online.Observation.ownerLabel]

@[simp] theorem startedLabels_filter_owner
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (transcript : Online.Transcript n) :
    Online.Transcript.startedLabels
      (transcript.filter (fun observation : Online.Observation n =>
        keep observation.ownerLabel)) =
      transcript.startedLabels.filter keep := by
  induction transcript with
  | nil => rfl
  | cons observation rest ih =>
      rw [List.filter_cons]
      by_cases hkeep : keep observation.ownerLabel
      · rw [if_pos (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.startedLabels,
            Online.Observation.ownerLabel]
      · rw [if_neg (by simpa using hkeep)]
        cases observation <;>
          simp_all [Online.Transcript.startedLabels,
            Online.Observation.ownerLabel]

theorem mem_startedLabels_of_mem_testResults
    {n : ℕ} {transcript : Online.Transcript n}
    {job : Fin n} {value : ℝ}
    (hmem : (job, value) ∈ transcript.testResults) :
    job ∈ transcript.startedLabels := by
  induction transcript with
  | nil => simp at hmem
  | cons observation rest ih =>
      cases observation with
      | testResult tested p =>
          simp only [Online.Transcript.testResults_testResult_cons,
            List.mem_cons] at hmem
          rcases hmem with heq | hrest
          · have hjob : tested = job := (congrArg Prod.fst heq).symm
            subst tested
            simp
          · exact List.mem_cons_of_mem tested (ih hrest)
      | processed processed =>
          exact ih (by simpa using hmem)
      | rawCompleted raw =>
          exact List.mem_cons_of_mem raw (ih (by simpa using hmem))

@[simp] theorem remainingTestResults_filter_owner
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    (transcript : Online.Transcript n) :
    Online.Transcript.remainingTestResults
      (transcript.filter (fun observation : Online.Observation n =>
        keep observation.ownerLabel)) =
      transcript.remainingTestResults.filter fun result => keep result.1 := by
  unfold Online.Transcript.remainingTestResults
  rw [testResults_filter_owner, processedLabels_filter_owner]
  simp only [List.filter_filter]
  apply List.filter_congr
  intro result hresult
  by_cases hkeep : keep result.1 <;>
    by_cases hprocessed : result.1 ∈ transcript.processedLabels <;>
      simp [hkeep, hprocessed]

/-- Every prefix of a completed canonical quota trace has touched exactly
the initial interval of virtual labels of the corresponding length. -/
theorem quotaRun_prefix_started_vals
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    {before after : Online.Transcript n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ after) :
    before.startedLabels.map Fin.val =
      List.range before.startedLabels.length := by
  have horder :=
    (quotaRun_completed hq u processing low).2.1.touchOrder
  rw [hfull, Online.Transcript.startedLabels_append,
    List.map_append] at horder
  have hlen : before.startedLabels.length ≤ n := by
    have hall := quotaRun_startedLabels_eq_ofFn hq u processing low
    rw [hfull, Online.Transcript.startedLabels_append] at hall
    have hfullLength := congrArg List.length hall
    simp only [List.length_append, List.length_ofFn] at hfullLength
    omega
  have htake := congrArg (List.take before.startedLabels.length) horder
  simpa [List.take_append_of_le_length, List.take_range, hlen] using htake

theorem quotaRun_prefix_test_vals
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    {before after : Online.Transcript n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ after) :
    before.testResults.map (fun result => result.1.val) =
      List.range before.testResults.length := by
  have horder := (quotaRun_completed hq u processing low).2.1.testOrder
  have hquota :=
    (quotaRun_completed hq u processing low).2.1
      |>.testResults_length_eq_quota_of_done hq
        (quotaRun_completed hq u processing low).2.2
  rw [hfull, Online.Transcript.testResults_append,
    List.map_append] at horder
  have hlen : before.testResults.length ≤ q := by
    have hfullLength := congrArg List.length horder
    simp only [List.length_append, List.length_map,
      List.length_range] at hfullLength
    rw [hfull, Online.Transcript.testResults_append,
      List.length_append] at hquota
    omega
  have htake := congrArg (List.take before.testResults.length) horder
  simpa [List.take_append_of_le_length, List.take_range, hlen] using htake

theorem testPhaseClosed_nextKeptTouch?_eq_none
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep]
    {before after : Online.Transcript n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ after)
    (hclosed : q ≤ before.testResults.length) :
    nextKeptTouch? n keep (fun job => decide (job.val < q))
        (before.filter fun observation => keep observation.ownerLabel) =
      none := by
  apply nextKeptTouch?_eq_none
  intro job heligible hkeep
  rw [startedLabels_filter_owner]
  apply List.mem_filter.mpr
  refine ⟨?_, by simpa using hkeep⟩
  have hlt : job.val < q := by simpa using heligible
  have hvalue : job.val ∈ List.range before.testResults.length := by
    simp
    omega
  rw [← quotaRun_prefix_test_vals hq u processing low hfull] at hvalue
  rcases List.mem_map.mp hvalue with ⟨⟨label, p⟩, hresult, heq⟩
  have hlabel : label = job := by
    apply Fin.ext
    simpa using heq
  subst label
  exact mem_startedLabels_of_mem_testResults hresult

/-- At a displayed canonical first touch, every smaller virtual label has
already been touched. -/
theorem smaller_started_before_quota_touch
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    {before after : Online.Transcript n} {observation : Online.Observation n}
    {job : Fin n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ observation :: after)
    (htouch : observationTouchLabel? observation = some job) :
    job ∉ before.startedLabels ∧
      ∀ other : Fin n, other.val < job.val →
        other ∈ before.startedLabels := by
  have hprefix := quotaRun_prefix_started_vals hq u processing low
    (before := before) (after := observation :: after) (by simpa using hfull)
  have haction := (quotaRun_followsStrategy u processing low).action_at hfull
  have hnext : RandomizedOptional.nextCanonicalTouch? n before = some job := by
    cases observation with
    | testResult tested value =>
        simp only [observationTouchLabel?, Option.some.injEq] at htouch
        subst tested
        unfold quotaStrategy at haction
        cases hsafe : safeLastLowPending? low before <;>
          simp [hsafe, Online.Observation.requestedAction] at haction
        split at haction
        next hlt => simpa using haction
        next hnot =>
          split at haction <;>
            simp_all [Online.Observation.requestedAction]
    | processed processed => simp [observationTouchLabel?] at htouch
    | rawCompleted raw =>
        simp only [observationTouchLabel?, Option.some.injEq] at htouch
        subst raw
        unfold quotaStrategy at haction
        cases hsafe : safeLastLowPending? low before <;>
          simp [hsafe, Online.Observation.requestedAction] at haction
        split at haction
        next hlt => simp at haction
        next hnot =>
          split at haction
          next selected hshort => simp at haction
          next hnone => simpa using haction
  have hfacts := (nextCanonicalTouch_some_iff.mp hnext)
  have hlength : job.val = before.startedLabels.length := hfacts.2
  constructor
  · intro hmem
    have hvalMem : job.val ∈ List.range before.startedLabels.length := by
      rw [← hprefix]
      exact List.mem_map.mpr ⟨job, hmem, rfl⟩
    simp [hlength] at hvalMem
  · intro other hlt
    have hvalMem : other.val ∈ List.range before.startedLabels.length := by
      simp [← hlength, hlt]
    rw [← hprefix] at hvalMem
    rcases List.mem_map.mp hvalMem with ⟨candidate, hcandidate, heq⟩
    have : candidate = other := by
      apply Fin.ext
      simpa using heq
    simpa [this] using hcandidate

theorem nextKeptTouch?_filter_owner_at_quota_touch
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep]
    (eligible : Fin n → Bool)
    {before after : Online.Transcript n} {observation : Online.Observation n}
    {job : Fin n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ observation :: after)
    (htouch : observationTouchLabel? observation = some job)
    (hkeep : keep job) (heligible : eligible job = true) :
    nextKeptTouch? n keep eligible
        (before.filter fun current => keep current.ownerLabel) = some job := by
  have hstarted := smaller_started_before_quota_touch hq u processing low
    hfull htouch
  apply nextKeptTouch?_eq_some keep eligible _ job hkeep heligible
  · rw [startedLabels_filter_owner]
    intro hmem
    exact hstarted.1 (List.mem_filter.mp hmem).1
  · intro other hlt hkeepOther
    rw [startedLabels_filter_owner]
    exact List.mem_filter.mpr ⟨hstarted.2 other hlt, by simpa using hkeepOther⟩

/-- Filtering a word preserves a kept final observation. -/
theorem getLast?_filter_owner_of_getLast?
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    {transcript : Online.Transcript n} {observation : Online.Observation n}
    (hlast : transcript.getLast? = some observation)
    (hkeep : keep observation.ownerLabel) :
    (transcript.filter fun current => keep current.ownerLabel).getLast? =
      some observation := by
  obtain ⟨before, rfl⟩ := List.getLast?_eq_some_iff.mp hlast
  simp [hkeep]

/-- A selected immediate-low owner remains selected after other owners are
deleted. -/
theorem safeLastLowPending?_filter_owner_of_some
    {n : ℕ} (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep]
    {transcript : Online.Transcript n} {job : Fin n}
    (hsafe : safeLastLowPending? low transcript = some job)
    (hkeep : keep job) :
    safeLastLowPending? low
        (transcript.filter fun observation => keep observation.ownerLabel) =
      some job := by
  unfold safeLastLowPending? at hsafe ⊢
  cases hlast : transcript.getLast? with
  | none => simp [hlast] at hsafe
  | some observation =>
      rw [hlast] at hsafe
      cases observation with
      | processed other => simp at hsafe
      | rawCompleted other => simp at hsafe
      | testResult tested value =>
          have hfacts :
              (low value = true ∧
                tested ∈ transcript.remainingTestResults.map Prod.fst) ∧
              tested = job := by
            simpa using hsafe
          rcases hfacts with ⟨⟨hlow, hpending⟩, heq⟩
          subst tested
          have hlastFiltered := getLast?_filter_owner_of_getLast? keep hlast hkeep
          rw [hlastFiltered]
          have hpending' : job ∈
              (Online.Transcript.remainingTestResults
                (transcript.filter fun observation =>
                  keep observation.ownerLabel)).map Prod.fst := by
            rw [remainingTestResults_filter_owner]
            rcases List.mem_map.mp hpending with ⟨result, hresult, heq⟩
            rcases result with ⟨label, processing⟩
            simp only at heq
            subst label
            apply List.mem_map.mpr
            exact ⟨(job, processing), List.mem_filter.mpr
              ⟨hresult, by simpa using hkeep⟩, rfl⟩
          simp only [hlow, Bool.true_and, decide_eq_true_eq,
            hpending', if_pos]

/-- Owner deletion cannot expose a spurious pending low job in a prefix of
a completed quota trace.  A low test is immediately followed by its process
operation, which has the same owner and is therefore deleted or retained
together with the test. -/
theorem safeLastLowPending?_filter_owner_of_none
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep]
    {before suffix : Online.Transcript n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ suffix)
    (hsafe : safeLastLowPending? low before = none) :
    safeLastLowPending? low
        (before.filter fun observation => keep observation.ownerLabel) =
      none := by
  by_contra hnot
  cases hfiltered : safeLastLowPending? low
      (before.filter fun observation => keep observation.ownerLabel) with
  | none => exact hnot hfiltered
  | some job =>
      unfold safeLastLowPending? at hfiltered
      cases hlast : (before.filter fun observation =>
          keep observation.ownerLabel).getLast? with
      | none => simp [hlast] at hfiltered
      | some observation =>
          rw [hlast] at hfiltered
          cases observation with
          | processed other => simp at hfiltered
          | rawCompleted other => simp at hfiltered
          | testResult tested value =>
              have hfacts :
                  (low value = true ∧
                    tested ∈
                      (Online.Transcript.remainingTestResults
                        (before.filter fun observation =>
                          keep observation.ownerLabel)).map Prod.fst) ∧
                  tested = job := by
                simpa using hfiltered
              rcases hfacts with ⟨⟨hlow, hpending⟩, heqJob⟩
              subst tested
              have htestFiltered :
                  Online.Observation.testResult job value ∈
                    before.filter fun observation =>
                      keep observation.ownerLabel :=
                List.mem_of_getLast? hlast
              have htest : Online.Observation.testResult job value ∈ before :=
                (List.mem_filter.mp htestFiltered).1
              have hkeep : keep job := by
                simpa [Online.Observation.ownerLabel] using
                  (List.mem_filter.mp htestFiltered).2
              rcases List.mem_map.mp hpending with
                ⟨⟨label, p⟩, hresult, heq⟩
              change label = job at heq
              subst label
              have hresultParts := List.mem_filter.mp hresult
              have hnotProcessedFiltered :
                  job ∉ Online.Transcript.processedLabels
                    (before.filter fun observation =>
                      keep observation.ownerLabel) :=
                of_decide_eq_true hresultParts.2
              have htestResult : (job, p) ∈ before.testResults := by
                have htestFiltered := hresultParts.1
                rw [testResults_filter_owner] at htestFiltered
                exact (List.mem_filter.mp htestFiltered).1
              have hnotProcessed : job ∉ before.processedLabels := by
                intro hprocessed
                apply hnotProcessedFiltered
                rw [processedLabels_filter_owner]
                exact List.mem_filter.mpr ⟨hprocessed, by simpa using hkeep⟩
              obtain ⟨left, right, hbefore⟩ := List.mem_iff_append.mp htest
              cases right with
              | nil =>
                  have hlastOriginal : before.getLast? =
                      some (.testResult job value) := by
                    rw [hbefore]
                    simp
                  have hpendingOriginal : job ∈
                      before.remainingTestResults.map Prod.fst := by
                    apply List.mem_map.mpr
                    exact ⟨(job, p), List.mem_filter.mpr
                      ⟨htestResult, by simpa using hnotProcessed⟩, rfl⟩
                  unfold safeLastLowPending? at hsafe
                  rw [hlastOriginal] at hsafe
                  simp [hlow, hpendingOriginal] at hsafe
              | cons next rest =>
                  have hdecomp :
                      (quotaRun q u processing low).config.transcript =
                        left ++ .testResult job value :: next ::
                          (rest ++ suffix) := by
                    rw [hfull, hbefore]
                    simp [List.append_assoc]
                  have hnext := quotaRun_low_test_immediately_processed
                    hq u processing low hdecomp hlow
                  subst next
                  apply hnotProcessed
                  apply (Online.processed_mem_iff_observation_mem before job).mpr
                  rw [hbefore]
                  simp

/-- The stable SPT choice survives deletion of candidates when the selected
candidate itself is retained.  The increasing-label hypothesis records the
tie-breaking order of the canonical test phase. -/
theorem shortestResult?_filter_of_pairwise
    {n : ℕ} (results : List (Fin n × ℝ))
    (keep : Fin n → Prop) [DecidablePred keep]
    (hpair : results.Pairwise
      (fun first second => first.1.val < second.1.val))
    {chosen : Fin n × ℝ}
    (hchosen : Online.shortestResult? results = some chosen)
    (hkeep : keep chosen.1) :
    Online.shortestResult?
        (results.filter fun result => keep result.1) = some chosen := by
  have hchosenMem := Online.shortestResult?_mem hchosen
  have hchosenFiltered : chosen ∈
      results.filter fun result => keep result.1 :=
    List.mem_filter.mpr ⟨hchosenMem, by simpa using hkeep⟩
  have hnonempty : (results.filter fun result => keep result.1) ≠ [] := by
    intro hempty
    simpa [hempty] using hchosenFiltered
  cases hfiltered : Online.shortestResult?
      (results.filter fun result => keep result.1) with
  | none =>
      exact (hnonempty
        ((Online.shortestResult?_eq_none_iff _).mp hfiltered)).elim
  | some filtered =>
      have hfilteredMem := Online.shortestResult?_mem hfiltered
      have hfilteredOriginal : filtered ∈ results :=
        (List.mem_filter.mp hfilteredMem).1
      have hforward := shortestResult_stableAtMost hpair hchosen
        hfilteredOriginal
      have hback := shortestResult_stableAtMost (hpair.filter _) hfiltered
        hchosenFiltered
      have hpForward : chosen.2 ≤ filtered.2 := by
        rcases hforward with hlt | ⟨heq, _⟩
        · exact hlt.le
        · exact heq.le
      have hpBack : filtered.2 ≤ chosen.2 := by
        rcases hback with hlt | ⟨heq, _⟩
        · exact hlt.le
        · exact heq.le
      have hp : chosen.2 = filtered.2 := le_antisymm hpForward hpBack
      have hlabelForward : chosen.1.val ≤ filtered.1.val := by
        rcases hforward with hlt | ⟨_, hlabel⟩
        · exfalso
          exact (lt_irrefl chosen.2 (by simpa [hp] using hlt))
        · exact hlabel
      have hlabelBack : filtered.1.val ≤ chosen.1.val := by
        rcases hback with hlt | ⟨_, hlabel⟩
        · exfalso
          exact (lt_irrefl filtered.2 (by simpa [hp] using hlt))
        · exact hlabel
      have hlabel : chosen.1 = filtered.1 := by
        apply Fin.ext
        exact le_antisymm hlabelForward hlabelBack
      have heq : chosen = filtered := by
        apply Prod.ext hlabel hp
      simpa [heq] using hfiltered

theorem shortestRemaining?_filter_owner_of_some
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    {transcript : Online.Transcript n} {job : Fin n}
    (hpair : transcript.remainingTestResults.Pairwise
      (fun first second => first.1.val < second.1.val))
    (hshort : transcript.shortestRemaining? = some job)
    (hkeep : keep job) :
    Online.Transcript.shortestRemaining?
      (transcript.filter fun observation =>
        keep observation.ownerLabel) = some job := by
  unfold Online.Transcript.shortestRemaining? at hshort ⊢
  cases hresult : Online.shortestResult? transcript.remainingTestResults with
  | none => simp [hresult] at hshort
  | some result =>
      have hlabel : result.1 = job := by simpa [hresult] using hshort
      rw [remainingTestResults_filter_owner]
      have hfiltered := shortestResult?_filter_of_pairwise
        transcript.remainingTestResults keep hpair hresult
        (by simpa [hlabel] using hkeep)
      rw [hfiltered]
      simp [hlabel]

theorem shortestRemaining?_filter_owner_of_none
    {n : ℕ} (keep : Fin n → Prop) [DecidablePred keep]
    {transcript : Online.Transcript n}
    (hshort : transcript.shortestRemaining? = none) :
    Online.Transcript.shortestRemaining?
      (transcript.filter fun observation =>
        keep observation.ownerLabel) = none := by
  unfold Online.Transcript.shortestRemaining? at hshort ⊢
  have hresultNone : Online.shortestResult?
      transcript.remainingTestResults = none := by
    cases hresult : Online.shortestResult? transcript.remainingTestResults with
    | none => rfl
    | some result => simp [hresult] at hshort
  have hempty := (Online.shortestResult?_eq_none_iff _).mp hresultNone
  rw [remainingTestResults_filter_owner, hempty]
  rfl

/-- One retained observation of the completed quota word is requested by
the owner-restricted strategy on the retained preceding prefix. -/
theorem keptQuotaStrategy_action_at
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep]
    {before after : Online.Transcript n}
    {observation : Online.Observation n}
    (hfull : (quotaRun q u processing low).config.transcript =
      before ++ observation :: after)
    (hkeep : keep observation.ownerLabel) :
    keptQuotaStrategy n q low keep
        (before.filter fun current => keep current.ownerLabel) =
      some observation.requestedAction := by
  have haction := (quotaRun_followsStrategy u processing low).action_at hfull
  cases observation with
  | testResult job value =>
      have hkeepJob : keep job := by simpa [Online.Observation.ownerLabel] using hkeep
      have htestAction : quotaStrategy n q low before = some (.test job) := by
        simpa [Online.Observation.requestedAction] using haction
      have hsafe : safeLastLowPending? low before = none := by
        unfold quotaStrategy at htestAction
        cases hsafe : safeLastLowPending? low before with
        | none => rfl
        | some selected => simp [hsafe] at htestAction
      have hsafeFiltered := safeLastLowPending?_filter_owner_of_none
        hq u processing low keep
        (before := before) (suffix := .testResult job value :: after)
        (by simpa using hfull) hsafe
      have htestMem : (job, value) ∈
          (quotaRun q u processing low).config.transcript.testResults := by
        apply (Online.testResult_mem_iff_observation_mem _ job value).mpr
        rw [hfull]
        simp
      have hlt : job.val < q :=
        ((quotaRun_completed hq u processing low).2.1
          |>.testResult_mem_iff_val_lt_of_done hq
            (quotaRun_completed hq u processing low).2.2 job).mp
          ⟨value, htestMem⟩
      have hnext := nextKeptTouch?_filter_owner_at_quota_touch
        hq u processing low keep (fun candidate => decide (candidate.val < q))
        hfull (job := job) rfl hkeepJob (by simpa using hlt)
      simp [keptQuotaStrategy, hsafeFiltered, hnext,
        Online.Observation.requestedAction]
  | processed job =>
      have hkeepJob : keep job := by simpa [Online.Observation.ownerLabel] using hkeep
      have hprocessAction : quotaStrategy n q low before =
          some (.process job) := by
        simpa [Online.Observation.requestedAction] using haction
      rcases quotaStrategy_process_cases hprocessAction with
        hsafe | ⟨hsafe, hclosed, hshort⟩
      · have hsafeFiltered := safeLastLowPending?_filter_owner_of_some
          low keep hsafe hkeepJob
        simp [keptQuotaStrategy, hsafeFiltered,
          Online.Observation.requestedAction]
      · have hsafeFiltered := safeLastLowPending?_filter_owner_of_none
          hq u processing low keep
          (before := before) (suffix := .processed job :: after)
          (by simpa using hfull) hsafe
        have htestClosed := testPhaseClosed_nextKeptTouch?_eq_none
          hq u processing low keep
          (before := before) (after := .processed job :: after)
          (by simpa using hfull) hclosed
        have hpair := quotaRun_prefix_remaining_pairwise
          hq u processing low
          (initial := before) (suffix := .processed job :: after)
          (by simpa using hfull)
        have hshortFiltered := shortestRemaining?_filter_owner_of_some
          keep hpair hshort hkeepJob
        simp [keptQuotaStrategy, hsafeFiltered, htestClosed,
          hshortFiltered, Online.Observation.requestedAction]
  | rawCompleted job =>
      have hkeepJob : keep job := by simpa [Online.Observation.ownerLabel] using hkeep
      have hrawAction : quotaStrategy n q low before = some (.raw job) := by
        simpa [Online.Observation.requestedAction] using haction
      have hrawFacts := quotaStrategy_raw_implies_no_remaining hrawAction
      have hsafe : safeLastLowPending? low before = none := by
        unfold quotaStrategy at hrawAction
        cases hsafe : safeLastLowPending? low before with
        | none => rfl
        | some selected => simp [hsafe] at hrawAction
      have hsafeFiltered := safeLastLowPending?_filter_owner_of_none
        hq u processing low keep
        (before := before) (suffix := .rawCompleted job :: after)
        (by simpa using hfull) hsafe
      have htestClosed := testPhaseClosed_nextKeptTouch?_eq_none
        hq u processing low keep
        (before := before) (after := .rawCompleted job :: after)
        (by simpa using hfull) hrawFacts.1
      have hshortFiltered := shortestRemaining?_filter_owner_of_none
        keep hrawFacts.2
      have hself :=
        (quotaRun_completed hq u processing low).2.1
          |>.selfProjection_eq_terminalWord hq
            (quotaRun_completed hq u processing low).2.2 job
      have hrawMem : Online.Observation.rawCompleted job ∈
          (quotaRun q u processing low).config.transcript := by
        rw [hfull]
        simp
      have hrawProjection : Online.Observation.rawCompleted job ∈
          (quotaRun q u processing low).config.transcript.pairProjection
            job job :=
        List.mem_filter.mpr ⟨hrawMem, by simp [Online.Observation.ownerLabel]⟩
      have hge : q ≤ job.val := by
        by_contra hnot
        have hlt : job.val < q := Nat.lt_of_not_ge hnot
        rw [if_pos hlt] at hself
        rw [hself] at hrawProjection
        simp at hrawProjection
      have hnext := nextKeptTouch?_filter_owner_at_quota_touch
        hq u processing low keep (fun candidate => decide (q ≤ candidate.val))
        hfull (job := job) rfl hkeepJob (by simpa using hge)
      simp [keptQuotaStrategy, hsafeFiltered, htestClosed,
        hshortFiltered, hnext, Online.Observation.requestedAction]

/-- Strategy agreement on a suffix, relative to an already displayed public
prefix. -/
def FollowsFrom
    {n : ℕ} (strategy : Online.Strategy n)
    (base suffix : Online.Transcript n) : Prop :=
  ∀ index : Fin suffix.length,
    strategy (base ++ suffix.take index.val) =
      some (suffix.get index).requestedAction

@[simp] theorem followsFrom_nil
    {n : ℕ} (strategy : Online.Strategy n)
    (base : Online.Transcript n) :
    FollowsFrom strategy base [] := by
  intro index
  exact Fin.elim0 index

theorem followsFrom_cons
    {n : ℕ} {strategy : Online.Strategy n}
    {base rest : Online.Transcript n} {observation : Online.Observation n}
    (hhead : strategy base = some observation.requestedAction)
    (htail : FollowsFrom strategy (base ++ [observation]) rest) :
    FollowsFrom strategy base (observation :: rest) := by
  intro index
  refine Fin.cases ?_ (fun tailIndex => ?_) index
  · simpa using hhead
  · have h := htail tailIndex
    simpa [FollowsFrom, List.append_assoc] using h

theorem followsFrom_cons_head
    {n : ℕ} {strategy : Online.Strategy n}
    {base rest : Online.Transcript n} {observation : Online.Observation n}
    (hfollow : FollowsFrom strategy base (observation :: rest)) :
    strategy base = some observation.requestedAction := by
  have h := hfollow ⟨0, by simp⟩
  simpa [FollowsFrom] using h

theorem followsFrom_cons_tail
    {n : ℕ} {strategy : Online.Strategy n}
    {base rest : Online.Transcript n} {observation : Online.Observation n}
    (hfollow : FollowsFrom strategy base (observation :: rest)) :
    FollowsFrom strategy (base ++ [observation]) rest := by
  intro index
  have h := hfollow index.succ
  simpa [FollowsFrom, List.append_assoc] using h

theorem followsStrategy_append_of_followsFrom
    {n : ℕ} {strategy : Online.Strategy n}
    {left right : Online.Transcript n}
    (hleft : left.FollowsStrategy strategy)
    (hright : FollowsFrom strategy left right) :
    (left ++ right).FollowsStrategy strategy := by
  induction right generalizing left with
  | nil => simpa using hleft
  | cons observation rest ih =>
      have hhead := followsFrom_cons_head hright
      have hleftNext := hleft.append observation hhead
      have htail := followsFrom_cons_tail hright
      have hrec := ih hleftNext htail
      simpa [List.append_assoc] using hrec

/-- The owner-filtered completed quota word follows the owner-restricted
quota strategy.  This is the central deterministic erasure simulation. -/
theorem quotaRun_filter_owner_follows
    {n q : ℕ} (hq : q ≤ n) (u : ℝ)
    (processing : Fin n → ℝ) (low : ℝ → Bool)
    (keep : Fin n → Prop) [DecidablePred keep] :
    Online.Transcript.FollowsStrategy (keptQuotaStrategy n q low keep)
      ((quotaRun q u processing low).config.transcript.filter
        fun observation => keep observation.ownerLabel) := by
  let whole := (quotaRun q u processing low).config.transcript
  have haux : ∀ (before todo : Online.Transcript n),
      whole = before ++ todo →
      FollowsFrom (keptQuotaStrategy n q low keep)
        (before.filter fun observation => keep observation.ownerLabel)
        (todo.filter fun observation => keep observation.ownerLabel) := by
    intro before todo hsplit
    induction todo generalizing before with
    | nil => exact followsFrom_nil _ _
    | cons observation rest ih =>
        by_cases hkeep : keep observation.ownerLabel
        · rw [List.filter_cons, if_pos (by simpa using hkeep)]
          apply followsFrom_cons
          · apply keptQuotaStrategy_action_at hq u processing low keep
              (before := before) (after := rest)
            · simpa [whole] using hsplit
            · exact hkeep
          · have hrec := ih (before ++ [observation]) (by
                simpa [List.append_assoc] using hsplit)
            simpa [List.filter_append, hkeep, List.append_assoc] using hrec
        · rw [List.filter_cons, if_neg (by simpa using hkeep)]
          have hrec := ih (before ++ [observation]) (by
            simpa [List.append_assoc] using hsplit)
          simpa [List.filter_append, hkeep, List.append_assoc] using hrec
  have hfollow := haux [] whole (by simp)
  simpa [FollowsFrom, whole, Online.Transcript.FollowsStrategy] using hfollow

/-! ## Extensionality in the low selector -/

theorem safeLastLowPending?_congr_on_processing
    {n : ℕ} (processing : Fin n → ℝ)
    (left right : ℝ → Bool) (transcript : Online.Transcript n)
    (hmatch : transcript.TestsMatch processing)
    (hagree : ∀ job, left (processing job) = right (processing job)) :
    safeLastLowPending? left transcript =
      safeLastLowPending? right transcript := by
  unfold safeLastLowPending?
  cases hlast : transcript.getLast? with
  | none => rfl
  | some observation =>
      cases observation with
      | processed job => rfl
      | rawCompleted job => rfl
      | testResult job value =>
          have hmem : (job, value) ∈ transcript.testResults :=
            (Online.testResult_mem_iff_observation_mem _ job value).mpr
              (List.mem_of_getLast? hlast)
          have hvalue : value = processing job := hmatch job value hmem
          rw [hvalue]
          simp only
          rw [hagree job]

theorem quotaStrategy_congr_on_processing
    {n q : ℕ} (processing : Fin n → ℝ)
    (left right : ℝ → Bool) (transcript : Online.Transcript n)
    (hmatch : transcript.TestsMatch processing)
    (hagree : ∀ job, left (processing job) = right (processing job)) :
    quotaStrategy n q left transcript = quotaStrategy n q right transcript := by
  unfold quotaStrategy
  rw [safeLastLowPending?_congr_on_processing processing left right transcript
    hmatch hagree]

theorem runFuel_quotaStrategy_congr_on_processing
    {n q : ℕ} (u : ℝ) (processing : Fin n → ℝ)
    (left right : ℝ → Bool)
    (hagree : ∀ job, left (processing job) = right (processing job))
    (fuel : ℕ) (config : Online.Config n)
    (hmatch : config.transcript.TestsMatch processing) :
    Online.runFuel (.finite u) (Online.fixedOracle processing)
        (quotaStrategy n q left) fuel config =
      Online.runFuel (.finite u) (Online.fixedOracle processing)
        (quotaStrategy n q right) fuel config := by
  induction fuel generalizing config with
  | zero => rfl
  | succ fuel ih =>
      simp only [Online.runFuel]
      have hstrategy := quotaStrategy_congr_on_processing (q := q) processing
        left right config.transcript hmatch hagree
      rw [hstrategy]
      cases haction : quotaStrategy n q right config.transcript with
      | none => simp [haction]
      | some action =>
          simp only [haction]
          cases hstep : config.step (.finite u)
              (Online.fixedOracle processing) action with
          | none => simp [hstep]
          | some next =>
              simp only [hstep]
              apply ih next
              exact Online.Config.step_preserves_testsMatch (.finite u)
                processing hmatch hstep

theorem quotaRun_congr_on_processing
    {n q : ℕ} (u : ℝ) (processing : Fin n → ℝ)
    (left right : ℝ → Bool)
    (hagree : ∀ job, left (processing job) = right (processing job)) :
    quotaRun q u processing left = quotaRun q u processing right := by
  unfold quotaRun Online.run
  apply runFuel_quotaStrategy_congr_on_processing u processing left right
    hagree
  exact Online.Transcript.testsMatch_nil processing

end

end QuotaRestriction
end RevealingOptimization
end SchedulingPaper
