import SchedulingPaper.FixedTestProcessCompletion
import Mathlib.Tactic

/-!
# Canonical trace grammar for test/process strategies

Every strategy built by `testProcessStrategy` has the same temporal
skeleton: tests occur in label order; a process before the end of testing is
the process immediately following the most recent test; all remaining
processes occur after every test.  This file records that skeleton as an
inductive grammar, independent of the numerical threshold policy.
-/

namespace SchedulingPaper.Online

noncomputable section

/-- Public traces generated by the common test/process control skeleton.
The side condition on process constructors records that a label is processed
at most once. -/
inductive TestProcessTrace : Transcript n → Prop
  | nil : TestProcessTrace []
  | test
      {transcript : Transcript n}
      (htrace : TestProcessTrace transcript)
      (hlt : transcript.testResults.length < n)
      (p : ℝ) :
      TestProcessTrace
        (transcript ++
          [.testResult
            ⟨transcript.testResults.length, hlt⟩ p])
  | immediate
      {transcript : Transcript n} {job : Label n} {p : ℝ}
      (htrace : TestProcessTrace transcript)
      (hlast :
        transcript.getLast? = some (.testResult job p))
      (hnotProcessed : job ∉ transcript.processedLabels) :
      TestProcessTrace (transcript ++ [.processed job])
  | tail
      {transcript : Transcript n} {job : Label n}
      (htrace : TestProcessTrace transcript)
      (hall : transcript.testResults.length = n)
      (hnotProcessed : job ∉ transcript.processedLabels) :
      TestProcessTrace (transcript ++ [.processed job])

theorem TestProcessTrace.testOrder
    {transcript : Transcript n}
    (htrace : TestProcessTrace transcript) :
    transcript.testResults.map (fun result => result.1.val) =
      List.range transcript.testResults.length := by
  induction htrace with
  | nil => simp
  | @test transcript htrace hlt p ih =>
      simp only [Transcript.testResults_append_testResult,
        List.map_append, List.map_singleton,
        List.length_append, List.length_singleton]
      rw [ih]
      simpa [Nat.add_comm] using
        (List.range_succ
          (n := transcript.testResults.length)).symm
  | immediate htrace hlast hnotProcessed ih =>
      simpa using ih
  | tail htrace hall hnotProcessed ih =>
      simpa using ih

theorem TestProcessTrace.testBound
    {transcript : Transcript n}
    (htrace : TestProcessTrace transcript) :
    transcript.testResults.length ≤ n := by
  induction htrace with
  | nil => simp
  | @test transcript htrace hlt p ih =>
      simp only [Transcript.testResults_append_testResult,
        List.length_append, List.length_singleton]
      omega
  | immediate htrace hlast hnotProcessed ih =>
      simpa using ih
  | tail htrace hall hnotProcessed ih =>
      simpa using ih

theorem TestProcessTrace.processedLabels_nodup
    {transcript : Transcript n}
    (htrace : TestProcessTrace transcript) :
    transcript.processedLabels.Nodup := by
  induction htrace with
  | nil => simp [Transcript.processedLabels]
  | test htrace hlt p ih =>
      simpa using ih
  | immediate htrace hlast hnotProcessed ih =>
      rw [Transcript.processedLabels_append_processed,
        List.nodup_append_comm]
      simp [ih, hnotProcessed]
  | tail htrace hall hnotProcessed ih =>
      rw [Transcript.processedLabels_append_processed,
        List.nodup_append_comm]
      simp [ih, hnotProcessed]

/-- One successful step selected by `testProcessStrategy` preserves the
canonical grammar. -/
theorem TestProcessTrace.step
    (cap : Cap) (oracle : Oracle n)
    {pending : Transcript n → Option (Label n)}
    (hpending : SelectsLastTest pending)
    {config next : Config n} {action : Action n}
    (hstruct : config.TestProcessInvariant)
    (htrace : TestProcessTrace config.transcript)
    (haction :
      testProcessStrategy pending config.transcript = some action)
    (hstep : config.step cap oracle action = some next) :
    TestProcessTrace next.transcript := by
  unfold testProcessStrategy at haction
  cases hp : pending config.transcript with
  | some job =>
      simp only [hp, Option.some.injEq] at haction
      subst action
      obtain ⟨p, hlast⟩ :=
        hpending config.transcript job hp
      have hjob : config.jobs job = .tested p :=
        hstruct.lastTest job p hlast
      have hnotProcessed :
          job ∉ config.transcript.processedLabels :=
        (hstruct.tested_iff job p).mp hjob |>.2
      simp only [Config.step, hjob,
        Option.some.injEq] at hstep
      subst next
      exact htrace.immediate hlast hnotProcessed
  | none =>
      simp only [hp] at haction
      split at haction
      next hlt =>
        simp only [Option.some.injEq] at haction
        subst action
        let job : Label n :=
          ⟨config.transcript.testResults.length, hlt⟩
        have hjob : config.jobs job = .untouched :=
          hstruct.labelAtTestCount_untouched rfl
        dsimp [job] at hjob
        simp only [Config.step, hjob,
          Option.some.injEq] at hstep
        subst next
        exact htrace.test hlt
          (oracle config.transcript
            ⟨config.transcript.testResults.length, hlt⟩)
      next hnotlt =>
        have hall :
            config.transcript.testResults.length = n := by
          have hbound := hstruct.testBound
          omega
        split at haction
        next job hshort =>
          simp only [Option.some.injEq] at haction
          subst action
          obtain ⟨p, hjob⟩ :=
            hstruct.shortestRemaining_tested hshort
          have hnotProcessed :
              job ∉ config.transcript.processedLabels :=
            (hstruct.tested_iff job p).mp hjob |>.2
          simp only [Config.step, hjob,
            Option.some.injEq] at hstep
          subst next
          exact htrace.tail hall hnotProcessed
        next hnone =>
          simp at haction

/-- Work-rank execution while retaining the canonical trace grammar, fixed
answers, and exact completion labels. -/
theorem runFuel_testProcessStrategy_completed_with_canonicalTrace
    (cap : Cap) (processingTime : Label n → ℝ)
    {pending : Transcript n → Option (Label n)}
    (hpending : SelectsLastTest pending) (extra : ℕ) :
    let result :=
      runFuel cap (fixedOracle processingTime)
        (testProcessStrategy pending)
        (2 * n + 1 + extra) (Config.initial n)
    result.reason = .strategyStopped ∧
      result.config.TestProcessInvariant ∧
      result.config.transcript.TestsMatch processingTime ∧
      result.config.FixedCompletionInvariant processingTime ∧
      TestProcessTrace result.config.transcript ∧
      ∀ job, result.config.jobs job = .done := by
  let Good : Config n → Prop :=
    fun config =>
      config.TestProcessInvariant ∧
        config.transcript.TestsMatch processingTime ∧
        config.FixedCompletionInvariant processingTime ∧
        TestProcessTrace config.transcript
  have hstop :
      ∀ config, Good config → config.remainingWork = 0 →
        testProcessStrategy pending config.transcript = none := by
    intro config hgood hzero
    exact testProcessStrategy_stop_of_zero hpending hgood.1 hzero
  have hprogress :
      ∀ config, Good config → 0 < config.remainingWork →
        WorkStep cap (fixedOracle processingTime)
          (testProcessStrategy pending) Good config := by
    intro config hgood hpos
    obtain ⟨action, next, haction, hstep, hnext, hwork⟩ :=
      testProcessStrategy_progress cap (fixedOracle processingTime)
        hpending hgood.1 hpos
    refine
      ⟨action, next, haction, hstep,
        ⟨hnext,
          Config.step_preserves_testsMatch cap processingTime
            hgood.2.1 hstep,
          Config.fixedCompletionInvariant_step
            cap processingTime hgood.1 hgood.2.1
              hgood.2.2.1 hstep,
          TestProcessTrace.step cap (fixedOracle processingTime)
            hpending hgood.1 hgood.2.2.2 haction hstep⟩,
        hwork⟩
  have hrun :=
    runFuel_completedNormally_of_workRank cap
      (fixedOracle processingTime) (testProcessStrategy pending)
      Good hstop hprogress (Config.initial n)
      ⟨Config.initial_testProcessInvariant n,
        Transcript.testsMatch_nil processingTime,
        Config.initial_fixedCompletionInvariant processingTime,
        TestProcessTrace.nil⟩ extra
  rw [Config.initial_remainingWork] at hrun
  exact
    ⟨hrun.1, hrun.2.1.1, hrun.2.1.2.1,
      hrun.2.1.2.2.1, hrun.2.1.2.2.2,
      hrun.2.2⟩

/-- The strengthened terminal package for the concrete ForcedPrefixUTE
execution. -/
theorem run_forcedPrefixUTEStrategy_canonicalTrace
    (n : ℕ) (u b : ℝ) (cap : Cap)
    (processingTime : Label n → ℝ) :
    let result :=
      run cap (fixedOracle processingTime)
        (forcedPrefixUTEStrategy n u b) (2 * n + 1)
    result.reason = .strategyStopped ∧
      result.config.TestProcessInvariant ∧
      result.config.transcript.TestsMatch processingTime ∧
      result.config.FixedCompletionInvariant processingTime ∧
      TestProcessTrace result.config.transcript ∧
      ∀ job, result.config.jobs job = .done := by
  unfold run
  rw [forcedPrefixUTEStrategy_eq_testProcessStrategy]
  simpa using
    runFuel_testProcessStrategy_completed_with_canonicalTrace
      cap processingTime
      (forcedPrefixPendingImmediate_selectsLastTest n
        (forcedPrefixCount n b) (uteThreshold u)) 0

end

end SchedulingPaper.Online
